---
# install docker host on all linux hosts
- name: install docker on host
  hosts: localhost
  tasks:
    - name: Docker | Install Docker | Install prerequisites
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      become: true
      become_method: sudo
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Docker | Install Docker | Add Docker’s official GPG key
      apt_key:
        id: 0EBFCD88
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
      become: true
      become_method: sudo

    - name: Docker | Install Docker | Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
      become: true
      become_method: sudo

    - name: Docker | Install Docker | Install Docker host
      apt:
        name: docker-ce
        update_cache: yes
        state: present
      become: true
      become_method: sudo


    - name: Docker | Install Docker | Create Docker group
      group:
        name: docker
        state: present

    - name: Docker | Install Docker | Add Docker group to local user
      user:
        name: ubuntu
        comment: "add user to docker group"
        groups: docker
        append: yes
      become: true
      become_method: sudo

    - name: Docker | Install Docker | Enable Docker service at boot
      systemd:
        name: docker
        enabled: yes
      become: true
      become_method: sudo

    - name: Docker | Install Docker | Install docker-compose
      shell: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
      become: true
      become_method: sudo

    - name: Docker | Install Docker | Set docker-compose as executable 
      file: 
        path: /usr/local/bin/docker-compose
        mode: "a+x"
      become: true
      become_method: sudo